#!/bin/bash
# Deploy HiveONNXConsumer to Ritual Chain using Foundry cast
#
# Usage:
#   ./scripts/deploy-onnx-consumer.sh [bondingCurveAddress]
#
# Requirements:
#   - PRIVATE_KEY in .env
#   - deployed-model-ids.json (generated by deploy_onnx_models.py)

set -e

# Load environment
source .env

# Get bonding curve address from args or use placeholder
BONDING_CURVE="${1:-0x0000000000000000000000000000000000000000}"

echo "Deploying HiveONNXConsumer..."
echo "  Account: $(cast wallet address $PRIVATE_KEY)"
echo "  Bonding Curve: $BONDING_CURVE"
echo ""

# Read model IDs from JSON
RISK_SCORING=$(cat deployed-model-ids.json | grep -o '"risk_scoring": "[^"]*"' | cut -d'"' -f4)
ANOMALY_DETECTION=$(cat deployed-model-ids.json | grep -o '"anomaly_detection": "[^"]*"' | cut -d'"' -f4)
SCAM_CLASSIFICATION=$(cat deployed-model-ids.json | grep -o '"scam_classification": "[^"]*"' | cut -d'"' -f4)
VOLATILITY_PREDICTION=$(cat deployed-model-ids.json | grep -o '"volatility_prediction": "[^"]*"' | cut -d'"' -f4)

echo "Models:"
echo "  Risk Scoring: $RISK_SCORING"
echo "  Anomaly Detection: $ANOMALY_DETECTION"
echo "  Scam Classification: $SCAM_CLASSIFICATION"
echo "  Volatility Prediction: $VOLATILITY_PREDICTION"
echo ""

# Deploy using forge create
echo "Deploying contract..."
forge create src/HiveONNXConsumer.sol:HiveONNXConsumer \
    --rpc-url https://rpc.ritualfoundation.org \
    --private-key $PRIVATE_KEY \
    --constructor-args \
        "$BONDING_CURVE" \
        "$(echo -n "$RISK_SCORING" | xxd -p -r)" \
        "$(echo -n "$ANOMALY_DETECTION" | xxd -p -r)" \
        "$(echo -n "$SCAM_CLASSIFICATION" | xxd -p -r)" \
        "$(echo -n "$VOLATILITY_PREDICTION" | xxd -p -r)"

echo ""
echo "✓ Deployment complete!"
